#antpool
version: "2.0"
services:
  mining:
    image: swanchain254/aleo_mainnet_antpool:v1.0.0
    env:
      - ACCOUNTNAME=rootabc
      - WORKNAME=work-001
    expose:
      - port: 5000
        as: 5000
deployment:
  mining:
    lagrange:
      count: 1
